
namespace Dhrutara.WriteWise.App.LocalStorage
{
    public class LocalContentProvider
    {
        private static IEnumerable<Content> ContentList => new List<Content>
        {
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy Birthday to my beautiful wife! On this special day, I want to thank you for all you do and all you are. You bring love and joy to my life, and I'm so grateful that you are my partner. I'm looking forward to all the wonderful things we will do and experiences we will share in the coming year. Wishing you a wonderful day and an amazing year ahead. I love you!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy Birthday, my love! Today is a special day because it marks the celebration of your birth, and I feel truly blessed to be able to share it with you. On this day, I want to take a moment to express my deep appreciation for all that you are and all that you do."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday to my beautiful wife! Today is all about you and I want you to know how much I love and appreciate you. You bring joy to my life and I'm so lucky to have you in it. Wishing you a day full of love and happiness, now and always."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday, my love. I look forward to celebrating many more birthdays with you in the years to come.I hope that today brings you all the love, happiness, and joy that you deserve. May this year be filled with many wonderful moments, and may we continue to grow together as a couple."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday to my beautiful wife!. As another year passes by and we celebrate your birthday, I am reminded once again of how blessed I am to have you in my life. You are the light that shines on my darkest days and the anchor that keeps me grounded when life gets tough."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday to my beautiful wife!. I hope this birthday is filled with all the joy, happiness, and love you deserve. May your heart be filled with warmth and your day be filled with all the things that make you smile. Thank you for being the love of my life and for sharing this journey with me. I am forever grateful for you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday, my love! Today is a special day because it's the day that you were born, and I am so grateful to have you in my life. You bring so much joy, love, and happiness into my world, and I can't imagine my life without you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday to my beautiful wife!. I hope this year brings you everything you've been dreaming of and more. May your days be filled with laughter, love, and all the things that make your heart happy. I promise to be here to celebrate with you every step of the way."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday, my dear! On this special day, I want to wish you the happiest of birthdays. You light up my world in ways that words cannot describe. Your smile, your laughter, and your kind heart are just a few of the many reasons why I love you so deeply."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Wife, "Happy birthday to my beautiful wife!. I feel incredibly blessed to have you in my life and to be able to celebrate another year of your amazing existence. May your day be filled with all the joy, love, and happiness that you deserve. May your heart be filled with warmth and your soul be uplifted."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday to the love of my life! I hope this day is filled with love, joy, and all the things that make you smile. I'm so lucky to have such a wonderful husband. You've been my rock, my confidant, and my best friend. I love you with all my heart and I can't wait to celebrate many more birthdays with you!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday, my love! You are the most amazing and special person in my life. The day you were born was the best day of my life.  Thanks for being there for me and for all your unconditional love and support. I hope your birthday is filled with lots of love and joy! Wishing you all the best, lots of love and hugs!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday, my love! Today is a special day because it marks the celebration of your birth, and I feel truly blessed to be able to share it with you. On this day, I want to take a moment to express my deep appreciation for all that you are and all that you do."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy birthday, my love. I look forward to celebrating many more birthdays with you in the years to come.I hope that today brings you all the love, happiness, and joy that you deserve. May this year be filled with many wonderful moments, and may we continue to grow together as a couple."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy birthday to my lovely husband!. As another year passes by and we celebrate your birthday, I am reminded once again of how blessed I am to have you in my life. You are the light that shines on my darkest days and the anchor that keeps me grounded when life gets tough."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday to the love of my life!. I hope this birthday is filled with all the joy, happiness, and love you deserve. May your heart be filled with warmth and your day be filled with all the things that make you smile. Thank you for being the love of my life and for sharing this journey with me. I am forever grateful for you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy birthday, my love! Today is a special day because it's the day that you were born, and I am so grateful to have you in my life. You bring so much joy, love, and happiness into my world, and I can't imagine my life without you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday to the love of my life!. I hope this year brings you everything you've been dreaming of and more. May your days be filled with laughter, love, and all the things that make your heart happy. I promise to be here to celebrate with you every step of the way."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy birthday, my love! I look forward to spending many more birthdays with you, creating new memories and sharing our lives together. Thank you for being my partner, my confidante, and my best friend. Happy birthday, my love. Here's to many more years of love and laughter!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Husband, "Happy Birthday to the love of my life!. I feel incredibly blessed to have you in my life and to be able to celebrate another year of your amazing existence. May your day be filled with all the joy, love, and happiness that you deserve. May your heart be filled with warmth and your soul be uplifted."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy birthday to the most amazing mother in the world! You have been my rock, my confidant, and my best friend. You have shown me what it means to be strong, kind, and compassionate. You have given me so much love and support throughout my life, and I am forever thankful for that. Wishing you a day full of joy and happiness, love and laughter!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy Birthday, Mom! You are an incredible woman who has been such an amazing role model for me. You have taught me so much about life and have always been there for me whenever I needed you. You have a heart of gold and I am so blessed to call you my mother. Wishing you a day filled with love and joy!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy birthday to the most amazing mother in the world! May your birthday be filled with all the happiness and joy you deserve. I wish you good health, love, and laughter always. Thank you for being the most amazing mother anyone could ever ask for. On this special day, I want to take a moment to express my love and appreciation for everything you do for me and our family. Happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy Birthday, Mom! You are the most beautiful person I know, both inside and out. Your kind heart, unwavering strength, and selfless nature inspire me every day. Your love and guidance have shaped me into the person I am today, and I am eternally grateful for that. Happy Birthday, Mom! I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy birthday to the most amazing mother in the world! On your special day, I want to take a moment to express how much you mean to me. You are more than just a mother to me, you are my role model, my confidant, and my best friend. You have always been there for me, offering unwavering support and love through every challenge and triumph."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy Birthday, Mom! On this special day, I want to take a moment to wish you the happiest of birthdays. You have been such a guiding light in my life and I am grateful for all that you have done for me. Today is a day to celebrate you and all that you mean to us. May your day be filled with joy, laughter and lots of love. I wish you good health, success, and happiness on this new journey around the sun."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy birthday to the most amazing mother in the world! You have been my rock, my confidant, and my best friend. You have shown me what it means to be strong, kind, and compassionate. You have given me so much love and support throughout my life, and I am forever thankful for that. Wishing you a day full of joy and happiness, love and laughter!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy Birthday, Mom! On this special day, I want to take a moment to wish you a very happy birthday! You are not just a father, but also a friend, a guide, and a mentor. You have always been there for me through thick and thin, and I cannot express how grateful I am to have you in my life. Happy Birthday, Mom! Thank you for being the best father in the world!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy birthday to the most amazing mother in the world! As I reflect on the many memories we have shared together, I am reminded of the love and support you have shown me over the years. Your unwavering faith in me and your encouragement to pursue my dreams have been invaluable, and I feel blessed to have a father like you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Mother, "Happy Birthday, Mom! Your strength, wisdom, and kindness inspire me every day, and I am proud to call you my father. Your dedication to your family and your work is truly admirable, and I hope to emulate these qualities in my own life. On this special day, I wish you all the joy, happiness, and blessings that life has to offer. May your day be filled with laughter, love, and warmth, and may all your dreams come true."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy Birthday to my wonderful father! You are the best father anyone could ask for and you mean the world to me. I love you so much and I'm grateful for all the time we've spent together. You have always been there for me and I am grateful for that. I hope you have a wonderful day!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy birthday, Father. You have been so amazing to me and I can't imagine my life without you. You always put others before yourself and I am so grateful for that. You are truly a wonderful man and I love you so much."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy Birthday to my wonderful father! May your birthday be filled with all the happiness and joy you deserve. I wish you good health, love, and laughter always. Thank you for being the most amazing mother anyone could ever ask for. On this special day, I want to take a moment to express my love and appreciation for everything you do for me and our family. Happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy birthday, Father. You are the most beautiful person I know, both inside and out. Your kind heart, unwavering strength, and selfless nature inspire me every day. Your love and guidance have shaped me into the person I am today, and I am eternally grateful for that. Happy Birthday, Dad! I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy Birthday to my wonderful father! On your special day, I want to take a moment to express how much you mean to me. You are more than just a mother to me, you are my role model, my confidant, and my best friend. You have always been there for me, offering unwavering support and love through every challenge and triumph."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy birthday, Father. Thank you for being such an amazing father. Your strength, kindness, and patience have been an inspiration to me and I hope to pass on these qualities to my own children someday.Happy Birthday, Dad! I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy Birthday to my wonderful father! You are the best father anyone could ask for and you mean the world to me. I love you so much and I'm grateful for all the time we've spent together. You have always been there for me and I am grateful for that. I hope you have a wonderful day!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy birthday, Father. On this special day, I want to take a moment to wish you the happiest of birthdays. You have been such a guiding light in my life and I am grateful for all that you have done for me. Today is a day to celebrate you and all that you mean to us. May your day be filled with joy, laughter and lots of love. I wish you good health, success, and happiness on this new journey around the sun."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy Birthday to my wonderful father! As I reflect on the many memories we have shared together, I am reminded of the love and support you have shown me over the years. Your unwavering faith in me and your encouragement to pursue my dreams have been invaluable, and I feel blessed to have a father like you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Father, "Happy birthday, On this special day, I want to take a moment to wish you a very happy birthday! You are not just a father, but also a friend, a guide, and a mentor. You have always been there for me through thick and thin, and I cannot express how grateful I am to have you in my life. Happy Birthday, Dad! Thank you for being the best father in the world!"),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy Birthday to my wonderful son! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my handsome and amazing son! You're the light of our lives, and we love you so much! You are so special and so loved, and we are so grateful to have you in our lives! We are so excited to see all the wonderful things you will accomplish in the next year! We love you so much!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my sweet son! Today, we celebrate the day that you came into this world and brightened our lives with your beautiful presence. I cannot believe how much you have grown and how much you have accomplished in this past year. You continue to amaze me every day with your kindness, intelligence, and sense of humor."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my handsome and amazing son! On this special day, I want you to know that you are loved beyond measure. You are the light of our lives, and we will always be here to support you, encourage you, and celebrate your achievements. May your birthday be filled with all the things that make you happy - cake, presents, laughter, and love."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy Birthday! Today is a special day because it's the day you came into our lives and made our world brighter and more beautiful. You have grown so much since the day you were born and every year you continue to amaze us with your kindness, creativity, and strength."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my handsome and amazing son! On this special day, we hope you feel loved and celebrated. May this year bring you new adventures, exciting discoveries, and all the happiness your heart can hold. May you continue to grow, learn, and thrive in every way possible."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy Birthday to my wonderful son! Happy Birthday to the most wonderful child in the world! I can hardly believe that another year has passed, and you are growing up so fast right before my eyes. It seems like just yesterday you were a tiny baby, and now you are a bright and beautiful human being!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my handsome and amazing son! I want you to know how much I love you and how grateful I am to have you in my life. You bring me so much joy and happiness every day, and I feel blessed to be your parent. Watching you grow and learn has been the greatest adventure of my life, and I can't wait to see what the future holds for you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy Birthday to my sweetheart! I want you to know how much I love you and how grateful I am to have you in my life. You bring me so much joy and happiness every day, and I feel blessed to be your parent. Watching you grow and learn has been the greatest adventure of my life, and I can't wait to see what the future holds for you. Happy Birthday, my love!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Son, "Happy birthday, my handsome and amazing son! On your special day, I hope all your dreams come true. May your life be filled with love, laughter, and endless possibilities. You have so much potential, and I know that you will achieve great things in this world. Always remember that I am here for you, no matter what. I am proud of the person you are becoming, and I will always support you in all your endeavors."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy Birthday to my sweetheart! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday! We love you more than words can express and we are honored to be your parents. Happy birthday, my love!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy birthday, my beautiful and amazing daughter! You're the light of our lives, and we love you so much! You are so special and so loved, and we are so grateful to have you in our lives! We are so excited to see all the wonderful things you will accomplish in the next year! We love you so much!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy Birthday to my wonderful daughter! Today, we celebrate the day that you came into this world and brightened our lives with your beautiful presence. I cannot believe how much you have grown and how much you have accomplished in this past year. You continue to amaze me every day with your kindness, intelligence, and sense of humor."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy birthday, my amazing daughter! On this special day, I want you to know that you are loved beyond measure. You are the light of our lives, and we will always be here to support you, encourage you, and celebrate your achievements. May your birthday be filled with all the things that make you happy - cake, presents, laughter, and love."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy Birthday to my sweet daughter! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday! We love you more than words can express and we are honored to be your parents. Happy birthday, my love!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy birthday, my handsome and amazing son! On this special day, we hope you feel loved and celebrated. May this year bring you new adventures, exciting discoveries, and all the happiness your heart can hold. May you continue to grow, learn, and thrive in every way possible."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy Birthday to my sweet daughter! Happy Birthday to the most wonderful child in the world! I can hardly believe that another year has passed, and you are growing up so fast right before my eyes. It seems like just yesterday you were a tiny baby, and now you are a bright and beautiful human being!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy birthday, my beautiful child! I want you to know how much I love you and how grateful I am to have you in my life. You bring me so much joy and happiness every day, and I feel blessed to be your parent. Watching you grow and learn has been the greatest adventure of my life, and I can't wait to see what the future holds for you."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy Birthday to my sweetheart! On your special day, I hope all your dreams come true. May your life be filled with love, laughter, and endless possibilities. You have so much potential, and I know that you will achieve great things in this world. Always remember that I am here for you, no matter what. I am proud of the person you are becoming, and I will always support you in all your endeavors."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Daughter, "Happy birthday, my amazing and lovely daughter! I want you to know how much I love you and how grateful I am to have you in my life. You bring me so much joy and happiness every day, and I feel blessed to be your parent. Watching you grow and learn has been the greatest adventure of my life, and I can't wait to see what the future holds for you. Happy Birthday, my love!"),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! I love you so much and I am grateful for all the amazing moments we've shared together. You are my best friend and I can't wait to see what the future holds for us. Have a wonderful birthday and a fantastic year ahead. May all your wishes come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! You are amazing and I love you so much! You are such a fun and loving person and I know that you will continue to be an amazing person. I hope that you have a wonderful birthday and that all of your dreams come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Dear brother! On this special day, I want to wish you the happiest of birthdays! You have always been an important part of my life, and I am grateful for the bond we share as siblings.Growing up with you has been an adventure, and I cherish all the memories we have made together. From playing silly pranks on each other to supporting one another through life's ups and downs, you have always been there for me."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! As you celebrate another year of life, I wish you good health, happiness, and success in all your endeavors. May this new year bring you many blessings and opportunities to fulfill your dreams and goals. Once again, happy birthday, dear brother! I love you and cannot imagine my life without you in it."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! May this year bring you endless joy, laughter, and unforgettable memories. May you continue to shine and achieve all your goals and dreams. I wish you success, good health, and happiness in all aspects of your life. Once again, happy birthday, my dear brother! I love you more than words can express, and I am so blessed to have you in my life."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! On your special day, I want to wish you the happiest birthday ever! You have been my partner in crime, my confidante, and my support system through thick and thin, and I am so grateful to have you as my brother. I am proud of the person you have become and all that you have achieved. You are not only my brother but also my role model. You inspire me to be a better person every day."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! I love you so much and I am grateful for all the amazing moments we've shared together. May this year bring you joy, success, and all the blessings that life has to offer. May you continue to grow and thrive in all aspects of your life. You deserve nothing but the best, and I am honored to call you my brother."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! Happy Birthday! On this special day, I want you to know how much you mean to me. You are not just my brother, but also my best friend and confidante. You have always been there for me, through thick and thin. Your unwavering support and love have helped me overcome many challenges in life. I cherish the memories we have created together, and look forward to creating many more in the years to come."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Dear brother! On this special day of yours, I want to take a moment to wish you a very happy birthday! You are not just my sibling but also my confidant, my friend, and my partner in all kinds of mischief. I feel so lucky to have you in my life, and I hope this year brings you all the joy and happiness you deserve."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Brother, "Happy birthday, my brother! May this birthday bring you lots of love, laughter, and blessings. May you achieve all your dreams and goals and make the most of every opportunity that comes your way. And may your life be filled with moments of happiness, peace, and contentment.Once again, happy birthday, dear brother."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday to my wonderful sister! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy birthday, my sister! You are the light of our lives, and we are so grateful for you. You make us laugh, you make us cry, and you are the best friend a person could ask for. You are the most beautiful person in the world, and we are so proud to have you as our sister."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday, my dear sister. I love you more than words can express. You bring so much joy and happiness to everyone around you, and I am constantly inspired by your kindness, strength, and unwavering spirit. As you celebrate another year of life, I hope you know how loved and appreciated you are. May your birthday be filled with all the things that make you happy and may all your dreams come true."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy birthday! Today is your special day and I want you to know how much you mean to me. You are not only my sister, but also my friend and confidante. I am so grateful to have you in my life. Thank you for being there for me, for supporting me, and for always believing in me. You are the best sister anyone could ask for and I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday to my wonderful sister! On this special day, I wish you all the happiness, love, and success that life has to offer. May your dreams come true and may you achieve everything you've ever wanted. May your life be filled with joy, laughter, and wonderful memories. Have a wonderful birthday and a fantastic year ahead. May all your wishes come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy birthday, my sister! You are not just my sibling, but my best friend, my confidante, and my partner in crime. I cherish all the memories we have created together and look forward to making many more in the years to come. May your day be filled with all the things that bring a smile to your face, from delicious cake to thoughtful gifts and everything in between."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday, dear sister. I love you to the moon and back. You are not just my sibling, but my best friend, my confidante, and my partner in crime. I cherish all the memories we have created together and look forward to making many more in the years to come. May you be surrounded by the people you love, and may your heart be filled with warmth and love."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy birthday, my sister! On this special day of yours, I want to take a moment to wish you a very happy birthday! You are not just my sibling but also my confidant, my friend, and my partner in all kinds of mischief. I feel so lucky to have you in my life, and I hope this year brings you all the joy and happiness you deserve."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday to my wonderful sister! Today, I hope that all your dreams come true and that your day is filled with love, joy, and happiness. May this year be the best one yet, filled with new adventures and exciting opportunities. Thank you for being such an amazing sister and for always being there for me. Cheers to another year of making memories, laughing until our bellies ache, and always having each other's backs. I love you more than words can express, and I wish you the happiest of birthdays!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Sister, "Happy Birthday! Today is all about celebrating you and the wonderful person you are. You bring so much joy and happiness into our lives, and I feel so lucky to have you as my sister. I want you to know how much you mean to me and how much I love you. You are my confidant, my cheerleader, and my partner in crime. I cherish all of our memories together and look forward to creating many more.May this new year of your life bring you all the love, happiness, and success you deserve."),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy birthday! I hope you have a day that is as wonderful as you are. You are so special, and I enjoy spending time with you. I hope that this birthday is as wonderful as you are."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy Birthday to my wonderful friend! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy birthday! Happy Birthday to one of the sweetest and most amazing people I know! Today is all about celebrating you and everything that makes you so special. I am grateful for your friendship and for all of the wonderful memories we've shared together. May your birthday be filled with lots of love, joy, and happiness."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy Birthday, my dear friend! Wishing you a day filled with love, laughter, and sweet memories that will last a lifetime. May all your dreams come true and may this year be the best one yet!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy birthday! I hope you have a day that is as wonderful as you are. On this special day, I just want to let you know how much you mean to me. You're not just a friend, you're family, and I'm so grateful to have you in my life. May your birthday be as amazing as you are!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy Birthday to my wonderful friend! Another year has gone by, and you're still as wonderful as ever! Happy Birthday, my dear friend. May your day be filled with all the things that make you happiest, and may your year ahead be even brighter than the last."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy birthday! To my partner in crime, my confidante, and my biggest cheerleader, Happy Birthday! You bring so much joy and laughter into my life, and I hope today you feel all the love and appreciation you deserve. Here's to another year of adventures and good times!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Sending you the warmest wishes on your birthday, my dear friend! May your heart be filled with love, your mind with peace, and your soul with gratitude. I hope this year brings you new opportunities, new experiences, and new friendships that will enrich your life in every way possible! Happy Birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy birthday! You are not just a friend to me, but a companion, a confidant, and a partner in crime. I am grateful for your presence in my life, and on your special day, I want to wish you all the best! May your birthday be as wonderful as you are, and may your dreams come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Friend, "Happy Birthday to my dearest friend! Wishing you a year filled with joy, laughter, and all the happiness you deserve. May this day bring you lots of love, presents, and sweet memories that you will cherish forever!"),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy birthday! I hope you have a day that is as wonderful as you are. You are so special, and I enjoy spending time with you. I hope that this birthday is as wonderful as you are."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy Birthday to my wonderful friend! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy birthday! Happy Birthday to one of the sweetest and most amazing people I know! Today is all about celebrating you and everything that makes you so special. I am grateful for your friendship and for all of the wonderful memories we've shared together. May your birthday be filled with lots of love, joy, and happiness."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy Birthday, my dear friend! Wishing you a day filled with love, laughter, and sweet memories that will last a lifetime. May all your dreams come true and may this year be the best one yet!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy birthday! I hope you have a day that is as wonderful as you are. On this special day, I just want to let you know how much you mean to me. You're not just a friend, you're family, and I'm so grateful to have you in my life. May your birthday be as amazing as you are!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy Birthday to my wonderful friend! Another year has gone by, and you're still as wonderful as ever! Happy Birthday, my dear friend. May your day be filled with all the things that make you happiest, and may your year ahead be even brighter than the last."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy birthday! To my partner in crime, my confidante, and my biggest cheerleader, Happy Birthday! You bring so much joy and laughter into my life, and I hope today you feel all the love and appreciation you deserve. Here's to another year of adventures and good times!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Sending you the warmest wishes on your birthday, my dear friend! May your heart be filled with love, your mind with peace, and your soul with gratitude. I hope this year brings you new opportunities, new experiences, and new friendships that will enrich your life in every way possible! Happy Birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy birthday! You are not just a friend to me, but a companion, a confidant, and a partner in crime. I am grateful for your presence in my life, and on your special day, I want to wish you all the best! May your birthday be as wonderful as you are, and may your dreams come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Boyfriend, "Happy Birthday to my dearest friend! Wishing you a year filled with joy, laughter, and all the happiness you deserve. May this day bring you lots of love, presents, and sweet memories that you will cherish forever!"),

            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy birthday! I hope you have a day that is as wonderful as you are. You are so special, and I enjoy spending time with you. I hope that this birthday is as wonderful as you are."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy Birthday to my wonderful friend! You are an amazing person who deserves all the love and happiness in the world. May your special day be filled with joy and may all your wishes come true. Wishing you a very happy birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy birthday! Happy Birthday to one of the sweetest and most amazing people I know! Today is all about celebrating you and everything that makes you so special. I am grateful for your friendship and for all of the wonderful memories we've shared together. May your birthday be filled with lots of love, joy, and happiness."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy Birthday, my dear friend! Wishing you a day filled with love, laughter, and sweet memories that will last a lifetime. May all your dreams come true and may this year be the best one yet!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy birthday! I hope you have a day that is as wonderful as you are. On this special day, I just want to let you know how much you mean to me. You're not just a friend, you're family, and I'm so grateful to have you in my life. May your birthday be as amazing as you are!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy Birthday to my wonderful friend! Another year has gone by, and you're still as wonderful as ever! Happy Birthday, my dear friend. May your day be filled with all the things that make you happiest, and may your year ahead be even brighter than the last."),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy birthday! To my partner in crime, my confidante, and my biggest cheerleader, Happy Birthday! You bring so much joy and laughter into my life, and I hope today you feel all the love and appreciation you deserve. Here's to another year of adventures and good times!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Sending you the warmest wishes on your birthday, my dear friend! May your heart be filled with love, your mind with peace, and your soul with gratitude. I hope this year brings you new opportunities, new experiences, and new friendships that will enrich your life in every way possible! Happy Birthday!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy birthday! You are not just a friend to me, but a companion, a confidant, and a partner in crime. I am grateful for your presence in my life, and on your special day, I want to wish you all the best! May your birthday be as wonderful as you are, and may your dreams come true!"),
            new Content(ContentType.Message, ContentCategory.Birthday,Relationship.Girlfriend, "Happy Birthday to my dearest friend! Wishing you a year filled with joy, laughter, and all the happiness you deserve. May this day bring you lots of love, presents, and sweet memories that you will cherish forever!"),


            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "Every day I thank the universe for sending me such an incredible soul mate like you. You are my rock, my confidant and my biggest supporter. You make my life so much brighter and I am so grateful to have you by my side. I love you with all my heart and I can't wait to spend a lifetime with you full of love and laughter."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "I am so blessed and thankful to have you in my life. You bring so much love and joy to my days, and I can’t express how much I appreciate you. Every moment I spend with you is a reminder of how lucky I am, and I will cherish them forever. You are my everything and I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "Every day I thank the universe for sending me such an incredible soul mate like you. You are my rock, my confidant and my biggest supporter. You make my life so much brighter and I am so grateful to have you by my side. I love you with all my heart and I can't wait to spend a lifetime with you full of love and laughter."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "I am so blessed and thankful to have you in my life. You bring so much love and joy to my days, and I can’t express how much I appreciate you. Every moment I spend with you is a reminder of how lucky I am, and I will cherish them forever. You are my everything and I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "My love, you light up my world like no one else can. Being with you makes every moment worth living for. I am so grateful to have you as my wife, and I promise to love you more each day. I may not say it often enough, but I want you to know that you mean everything to me."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "Dearest wife, you are the missing puzzle piece in my life that completes me. Your smile, your touch, and your love make my life beautiful. I cannot imagine spending a day without you. I love you more than words can say. Your love has filled my life with so much joy and happiness, and I cherish every moment we spend together. I am blessed to call you my wife."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "My soulmate, you are the one I want to spend the rest of my life with. You make my heart skip a beat every time I see you. I thank the stars above for bringing us together, and I promise to cherish and love you for all eternity."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "My love, as I wake up every morning next to you, I am filled with a sense of joy and gratitude. You are the light of my life, and I cherish every moment spent with you. I love you more and more with each passing day, and I am grateful to have you as my wife."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "To the most beautiful woman in the world, my heart beats only for you. Your love fills me with strength and your presence brings me peace. You are the embodiment of love and kindness, and I am so lucky to call you my wife. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Wife, "My love, I am so grateful for the life we share together. You are the light that brightens up my every day, and I thank the universe for bringing us together. I love you more than words can express. You are the most beautiful thing that has ever happened to me. "),

            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My love for you grows stronger with each passing day. You are my rock, my confidante, and my best friend. You bring so much joy and laughter into my life and I'm so blessed to have you in it. I want you to know that I will always be here for you and I will always love you with all of my heart. "),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My love you are the most romantic person I know and I love all the special moments we share together. I'm so grateful for all the moments we have shared and all the memories we will make in the future. I love you, now and always."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My love for you grows stronger with each passing day. You are my rock, my confidante, and my best friend. You bring so much joy and laughter into my life and I'm so blessed to have you in it. I want you to know that I will always be here for you and I will always love you with all of my heart. "),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My love you are the most romantic person I know and I love all the special moments we share together. I'm so grateful for all the moments we have shared and all the memories we will make in the future. I love you, now and always."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My dearest husband, as I wake up next to you every morning, my heart fills with love and gratitude. You make my world a better place with your presence, and I cannot imagine my life without you. You are my soulmate, my partner, my everything. Thank you for being my rock and for always supporting me through thick and thin. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "To my loving husband, I just wanted to take a moment to tell you how much you mean to me. Your love and devotion have brought so much happiness and joy into my life. Every day spent with you feels like a blessing, and I cherish every moment we share. I promise to love you unconditionally and stand by your side always. You are the love of my life, and I cannot wait to grow old with you."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My love, every day with you is a new adventure. You make me feel so loved and cherished, and I am grateful for every moment we spend together. I want you to know that I love you more than anything in this world. Thank you for being my partner, my best friend, and the love of my life."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "Dearest husband, I wanted to take a moment to tell you how much you mean to me. Your love is like a warm blanket on a cold night, it makes everything feel better. I am so lucky to have you in my life, and I am grateful for every moment we have shared. I promise to always stand by your side and support you, no matter what comes our way. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "My dearest husband, every moment spent with you is a blessing in my life. Your love, care, and affection make my heart skip a beat every time I think about you. I am so grateful for your presence in my life, and I promise to cherish and love you forever."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Husband, "To my darling husband, you are the love of my life and my soulmate. Your smile, your touch, and your love make my heart race with excitement and joy. I am so lucky to have you as my partner, and I promise to always be there for you, through thick and thin. You are my forever and always."),

            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "Every day I thank the universe for sending me such an incredible soul mate like you. You are my rock, my confidant and my biggest supporter. You make my life so much brighter and I am so grateful to have you by my side. I love you with all my heart and I can't wait to spend a lifetime with you full of love and laughter."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "I am so blessed and thankful to have you in my life. You bring so much love and joy to my days, and I can’t express how much I appreciate you. Every moment I spend with you is a reminder of how lucky I am, and I will cherish them forever. You are my everything and I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "My love, every moment with you feels like a fairytale come true. Your touch, your smile, your laugh, they all fill me with so much joy and happiness. I am grateful to have you in my life, and I promise to cherish and love you for as long as I live."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "Hey beautiful, just wanted to remind you how much you mean to me. You are the light in my life, the beating of my heart, and the reason for my smile. I love you more than words can express, and I can't wait to spend the rest of my life making you happy."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "My love, every moment spent with you feels like a fairytale come true. Your touch, your smile, your laughter - everything about you makes my heart skip a beat. I feel so grateful to have you in my life and I can't imagine a future without you. I love you more than words could ever express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "Dearest, you light up my world in ways I never knew were possible. Your presence fills my heart with warmth and joy, and I cherish every moment we spend together. With you, I feel like anything is possible and there's nothing we can't overcome. You are my soulmate, my best friend, and my everything. I love you more and more each day."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "My love, every time I see your face, my heart fills with an overwhelming feeling of joy and gratitude. You make every day brighter just by being in it, and I thank the universe for bringing you into my life. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "Dearest, I can't stop thinking about you. You are the first thing on my mind in the morning and the last thing before I drift off to sleep. You are my heart's home, my soulmate, and my forever love. I am grateful for every moment we spend together, and I can't wait to create many more memories with you. I love you endlessly."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "My love, as I lay here in bed, I can't help but think about how lucky I am to have you in my life. You are my sunshine on a cloudy day, my rock when I need support, and my partner in everything. I love you more than words can express, and I can't wait to spend the rest of my life making you feel just as loved and cherished as you make me feel every day."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Girlfriend, "Sweetheart, I just wanted to take a moment to tell you how much I appreciate you. You are the reason I wake up with a smile on my face every morning, and the thought of you makes my heart skip a beat. I love the way you laugh, the way you hold my hand, and the way you make me feel like the luckiest person in the world. Thank you for being my everything, and for making every day better just by being in it."),

            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love for you grows stronger with each passing day. You are my rock, my confidante, and my best friend. You bring so much joy and laughter into my life and I'm so blessed to have you in it. I want you to know that I will always be here for you and I will always love you with all of my heart. "),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love you are the most romantic person I know and I love all the special moments we share together. I'm so grateful for all the moments we have shared and all the memories we will make in the future. I love you, now and always."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My dearest love, every moment spent with you is a treasure that I will always cherish. You are the sunshine in my life, and I cannot imagine my world without you. I love you more than words can express, and I promise to always be here for you, through thick and thin. You are my forever and always."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love, you are the most beautiful thing that has ever happened to me. Your smile, your laughter, your touch - they all make my heart skip a beat. I thank the universe every day for bringing us together, and I promise to love you with all my heart, now and forever. You are the missing puzzle piece that completes me, and I cannot wait to spend the rest of my life with you."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love, I just wanted to take a moment to let you know how much you mean to me. You are the light in my life, the one who makes everything better just by being there. I feel so lucky to have you by my side, and I cherish every moment we spend together. I love you more than words can express, and I can't wait to see what our future holds. Thank you for being my everything."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "Hey handsome, just wanted to remind you how much I adore you. You are my rock, my support system, and my best friend. I love how we can talk about anything and everything, and how you always know just what to say to make me feel better. You make me feel loved and cherished, and I can't imagine my life without you. Thank you for being the most amazing boyfriend a girl could ask for. I love you to the moon and back."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love, every moment spent with you feels like a fairytale come true. You have filled my life with so much joy and love, and I am grateful for every single day I get to spend with you. You are my forever and always, and I cannot imagine a life without you. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "To my darling boyfriend, every time I look into your eyes, my heart skips a beat. You are the missing puzzle piece in my life, and I feel complete with you by my side. Your love is a soothing balm to my soul, and I feel so blessed to have you in my life. I love you now and always, and I cannot wait to spend forever with you."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My love, every moment spent with you is a treasure. You make my heart skip a beat and my soul feel alive. I am grateful to have you in my life and cherish every memory we make together. You are the missing piece in my life that completes me. I love you more than words can express."),
            new Content(ContentType.Message, ContentCategory.Romantic,Relationship.Boyfriend, "My sweetest, I am so lucky to have you as my partner in life. Your love fills my heart with joy and happiness. I love the way you look at me, the way you hold my hand, and the way you make me feel. Being with you is like a dream come true. Thank you for being my rock and supporting me through thick and thin. You are my forever and always."),
        };
        public LocalContentProvider()
        {
            SupportedContentTypes = ContentList.Select(x => x.ContentType).Distinct();
            SupportedContentCategories = ContentList.Select(x => x.Category).Distinct();
            SupportedRelationships = ContentList.Select(x => x.Relationship).Distinct();
        }

        public IEnumerable<ContentType> SupportedContentTypes { get; init; }
        public IEnumerable<ContentCategory> SupportedContentCategories { get; init; }
        public IEnumerable<Relationship> SupportedRelationships { get; init; }

        public string[] GetContent(ContentType contentType, ContentCategory category, Relationship? relationship)
        {
            List<string> texts = ContentList
                .Where(x => x.ContentType == contentType && x.Category == category && x.Relationship == relationship)
                .Select(x => x.Text)
                .ToList();

            if (texts.Any())
            {
                Random random = new();
                int index = random.Next(0, texts.Count - 1);

                string text = texts[index];

                return text.Split('.');
            }
            else
            {
                return new string[] {"Couldn't find a match.", "Please try gain later or try different options" };
            }
        }

        private record Content(ContentType ContentType, ContentCategory Category, Relationship Relationship, string Text);
    }
}
